"""Add barcode to products

Revision ID: 008ded628057
Revises: 5217cdb103dd
Create Date: 2025-08-12 20:01:40.355928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008ded628057'
down_revision = '5217cdb103dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_column('barcode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barcode', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
