"""Update remote_id column

Revision ID: 0873ffd192d7
Revises: 4961e01b0f8b
Create Date: 2025-08-30 10:50:11.934178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0873ffd192d7'
down_revision = '4961e01b0f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('businesses_remote_id_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('businesses_remote_id_key'), ['remote_id'])

    # ### end Alembic commands ###
