"""Add remaining_balance column to FutureOrder

Revision ID: 1682ab88f7e6
Revises: 40b60e6e7874
Create Date: 2025-08-28 18:02:44.205934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1682ab88f7e6'
down_revision = '40b60e6e7874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('future_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remaining_balance', sa.Float(), nullable=True))

    # Manually added step to populate existing rows with a default value
    op.execute('UPDATE future_orders SET remaining_balance = total_amount WHERE remaining_balance IS NULL')
    
    with op.batch_alter_table('future_orders', schema=None) as batch_op:
        batch_op.alter_column('remaining_balance',
               existing_type=sa.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('future_orders', schema=None) as batch_op:
        batch_op.drop_column('remaining_balance')

    # ### end Alembic commands ###