"""Add Creditor and Debtor models (corrected foreign key)

Revision ID: 1a53be3b352c
Revises: 243228af527d
Create Date: 2025-08-01 13:34:40.478992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a53be3b352c'
down_revision = '243228af527d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creditors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creditors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creditors_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creditors_company_id'), ['company_id'], unique=False)

    op.create_table('debtors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('debtors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_debtors_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_debtors_company_id'), ['company_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debtors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debtors_company_id'))
        batch_op.drop_index(batch_op.f('ix_debtors_business_id'))

    op.drop_table('debtors')
    with op.batch_alter_table('creditors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creditors_company_id'))
        batch_op.drop_index(batch_op.f('ix_creditors_business_id'))

    op.drop_table('creditors')
    # ### end Alembic commands ###
