"""Add total_creditors and total_debtors to Company model

Revision ID: 243228af527d
Revises: 28b170b90ed5
Create Date: 2025-07-31 18:05:47.644867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '243228af527d'
down_revision = '28b170b90ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_creditors', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_debtors', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('total_debtors')
        batch_op.drop_column('total_creditors')

    op.create_table('transactions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('transaction_id_display', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('transaction_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('customer_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('original_transaction_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('transactions_business_id_fkey')),
    sa.ForeignKeyConstraint(['original_transaction_id'], ['transactions.id'], name=op.f('transactions_original_transaction_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('transactions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_pkey')),
    sa.UniqueConstraint('transaction_id_display', name=op.f('transactions_transaction_id_display_key'))
    )
    # ### end Alembic commands ###
