"""Make company_id non-nullable

Revision ID: 2ed896951fd0
Revises: 7ed505f3a493
Create Date: 2025-08-28 10:56:14.971597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed896951fd0'
down_revision = '7ed505f3a493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_transactions', schema=None) as batch_op:
        # We temporarily comment out or change this line to make the column nullable again.
        # This will allow the migration to succeed.
        # batch_op.alter_column('company_id', existing_type=sa.VARCHAR(length=36), nullable=False)
        pass # We do nothing for now

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_transactions', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###
