"""Initial schema after full reset

Revision ID: 3dbf8569c934
Revises: 
Create Date: 2025-08-15 12:35:07.674667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dbf8569c934'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_records_business_id'))
        batch_op.drop_index(batch_op.f('ix_sales_records_transaction_id'))
        batch_op.drop_constraint(batch_op.f('sales_records_reference_number_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('sales_records_reference_number_key'), ['reference_number'])
        batch_op.create_index(batch_op.f('ix_sales_records_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_records_business_id'), ['business_id'], unique=False)

    # ### end Alembic commands ###
