"""Add recorded_by to CompanyTransaction

Revision ID: 40b60e6e7874
Revises: 2ed896951fd0
Create Date: 2025-08-28 11:12:26.757733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b60e6e7874'
down_revision = '2ed896951fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recorded_by', sa.String(length=36), nullable=True))
        batch_op.alter_column('company_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.create_foreign_key(None, 'user', ['recorded_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('company_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_column('recorded_by')

    # ### end Alembic commands ###
