"""Allow nullable pickup_date

Revision ID: 427576b0cf3e
Revises: 0873ffd192d7
Create Date: 2025-08-30 18:49:45.892772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427576b0cf3e'
down_revision = '0873ffd192d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('future_orders', schema=None) as batch_op:
        batch_op.alter_column('pickup_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('future_orders', schema=None) as batch_op:
        batch_op.alter_column('pickup_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
