"""Add date_recorded to RentalRecord

Revision ID: 4961e01b0f8b
Revises: 1682ab88f7e6
Create Date: 2025-08-28 18:59:05.375930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4961e01b0f8b'
down_revision = '1682ab88f7e6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_records', schema=None) as batch_op:
        # Step 1: Add the column as nullable=True first
        batch_op.add_column(sa.Column('date_recorded', sa.DateTime(), nullable=True))

    # Step 2: Populate existing rows with a default value (e.g., current timestamp)
    # This is crucial for existing records before setting NOT NULL
    op.execute('UPDATE rental_records SET date_recorded = NOW() WHERE date_recorded IS NULL')

    with op.batch_alter_table('rental_records', schema=None) as batch_op:
        # Step 3: Alter the column to be nullable=False
        batch_op.alter_column('date_recorded',
               existing_type=sa.DateTime(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_records', schema=None) as batch_op:
        batch_op.drop_column('date_recorded')

    # ### end Alembic commands ###
