"""Add markup_percentage_pharmacy to InventoryItem

Revision ID: 4c2c7eb0e506
Revises: 1340fbbf7be0
Create Date: 2025-08-19 10:18:46.353027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2c7eb0e506'
down_revision = '1340fbbf7be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('markup_percentage_pharmacy', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.alter_column('transaction_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.alter_column('transaction_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_column('markup_percentage_pharmacy')

    # ### end Alembic commands ###
