"""Add barcode to products

Revision ID: 5217cdb103dd
Revises: b9a5129f63f5
Create Date: 2025-08-12 19:36:52.655055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5217cdb103dd'
down_revision = 'b9a5129f63f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('inventory_items_barcode_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('inventory_items_barcode_key'), ['barcode'])

    # ### end Alembic commands ###
