"""Add partial unique index for barcode to allow multiple NULLs

Revision ID: 8d26cab9393e
Revises: afa94dcacb37
Create Date: 2025-08-22 13:52:04.646046

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d26cab9393e'
down_revision = 'afa94dcacb37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('future_orders', schema=None) as batch_op:
        batch_op.drop_column('date_ordered')

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('inventory_items_barcode_key'), type_='unique')
        batch_op.create_index('idx_unique_active_barcode', ['barcode'], unique=True, postgresql_where=sa.text('barcode IS NOT NULL'))

    with op.batch_alter_table('rental_records', schema=None) as batch_op:
        batch_op.drop_column('date_recorded')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_recorded', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_index('idx_unique_active_barcode', postgresql_where=sa.text('barcode IS NOT NULL'))
        batch_op.create_unique_constraint(batch_op.f('inventory_items_barcode_key'), ['barcode'])

    with op.batch_alter_table('future_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_ordered', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
