"""Add markup_percentage_pharmacy to inventory_items

Revision ID: 915b6ec1a353
Revises: c9c4183f9e34
Create Date: 2025-08-20 12:56:55.780419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915b6ec1a353'
down_revision = 'c9c4183f9e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('synced_to_remote',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(false)'))

    with op.batch_alter_table('company_transactions', schema=None) as batch_op:
        batch_op.alter_column('synced_to_remote',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(false)'))

    with op.batch_alter_table('creditors', schema=None) as batch_op:
        batch_op.alter_column('synced_to_remote',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(false)'))

    with op.batch_alter_table('debtors', schema=None) as batch_op:
        batch_op.alter_column('synced_to_remote',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(false)'))

    with op.batch_alter_table('future_orders', schema=None) as batch_op:
        batch_op.alter_column('synced_to_remote',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(false)'))

    with op.batch_alter_table('hirable_items', schema=None) as batch_op:
        batch_op.alter_column('synced_to_remote',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(false)'))

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('markup_percentage_pharmacy', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.alter_column('synced_to_remote',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(false)'))

    with op.batch_alter_table('rental_records', schema=None) as batch_op:
        batch_op.drop_column('synced_to_remote')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('synced_to_remote', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=True))

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.alter_column('synced_to_remote',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(false)'))
        batch_op.drop_column('markup_percentage_pharmacy')

    with op.batch_alter_table('hirable_items', schema=None) as batch_op:
        batch_op.alter_column('synced_to_remote',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(false)'))

    with op.batch_alter_table('future_orders', schema=None) as batch_op:
        batch_op.alter_column('synced_to_remote',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(false)'))

    with op.batch_alter_table('debtors', schema=None) as batch_op:
        batch_op.alter_column('synced_to_remote',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(false)'))

    with op.batch_alter_table('creditors', schema=None) as batch_op:
        batch_op.alter_column('synced_to_remote',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(false)'))

    with op.batch_alter_table('company_transactions', schema=None) as batch_op:
        batch_op.alter_column('synced_to_remote',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(false)'))

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('synced_to_remote',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(false)'))

    # ### end Alembic commands ###
