"""Add synced_to_remote to SaleRecord

Revision ID: e12854c2e565
Revises: b8f0cf3bd73d
Create Date: 2025-08-13 17:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # Import postgresql dialect


# revision identifiers, used by Alembic.
revision = 'e12854c2e565'
down_revision = 'b8f0cf3bd73d' # Your previous revision ID
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # --- FIX FOR businesses.last_updated NotNullViolation ---
    # 1. Add 'last_updated' to 'businesses' allowing NULLs temporarily
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True)) # Temporarily nullable=True

    # 2. Populate 'last_updated' for existing rows
    # IMPORTANT: Use op.execute() for DDL/DML statements directly
    op.execute(
        sa.text("UPDATE businesses SET last_updated = NOW() WHERE last_updated IS NULL")
    )

    # 3. Alter 'last_updated' to be NOT NULL (after it's populated)
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.alter_column('last_updated', existing_type=sa.DateTime(), nullable=False)
    # --- END FIX ---


    # --- ORIGINAL MIGRATION FOR SaleRecord.synced_to_remote ---
    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('synced_to_remote', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # --- Downgrade for SaleRecord.synced_to_remote ---
    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.drop_column('synced_to_remote')
    # --- END Downgrade for SaleRecord.synced_to_remote ---

    # --- Downgrade for businesses.last_updated ---
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('last_updated')
    # --- END Downgrade for businesses.last_updated ---

    # ### end Alembic commands ###