"""Add synced_to_remote to SalesRecord

Revision ID: 81b6399785b8
Revises: bb521f4fd878
Create Date: 2025-08-23 18:25:26.319803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b6399785b8'
down_revision = 'bb521f4fd878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('synced_to_remote', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        batch_op.drop_column('synced_to_remote')

    # ### end Alembic commands ###
