"""Add last_synced_at to business

Revision ID: bb521f4fd878
Revises: 1bb99ace1676
Create Date: 2025-08-23 18:11:03.391254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb521f4fd878'
down_revision = '1bb99ace1676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_synced_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('last_synced_at')

    # ### end Alembic commands ###
