"""Add remote_id to Business model

Revision ID: f9fe4f99f1c5
Revises: 81b6399785b8
Create Date: 2025-08-23 20:01:21.031307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9fe4f99f1c5'
down_revision = '81b6399785b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remote_id', sa.String(length=36), nullable=True))
        # This is the line that was missing the 'name' parameter. We'll add it.
        batch_op.create_unique_constraint('uq_businesses_remote_id', ['remote_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_constraint('uq_businesses_remote_id', type_='unique')
        batch_op.drop_column('remote_id')

    # ### end Alembic commands ###